name: fulltech
description: FULLTECH Flutter app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  file_picker: ^8.1.7
  open_filex: ^4.5.0
  pdf: ^3.11.1
  printing: ^5.13.4
  url_launcher: ^6.3.1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  uuid: 4.5.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/features/perfil/assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/features/perfil/assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/features/perfil/assets/images/
